pipeline {
    agent any
    parameters {
      text(name: 'VARS_CONTENT', defaultValue: 'clevercards-business-api\nclevergift-api\nclevergift-core ', description: 'Release Branch')
    }
    stages {
        stage('Create textfile.txt file') {
          steps {
            writeFile file: "${WORKSPACE}/textfile.txt", text: params.VARS_CONTENT
          }
        }
        stage('Check File Contents') {
            steps {
                script {
                    def inputFile = "${WORKSPACE}/textfile.txt" // Replace with your text file path

                    // Read the file contents and look for the keywords
                    sh "grep -E '(clevercards-business-api|CHICKEN)' ${inputFile} > keyword_found.txt || true"
                    def keywordsFound = readFile('keyword_found.txt').trim().split('\n')

                    def yamlContent = ""
                    keywordsFound.each { keyword ->
                        if (keyword.trim()) {
                            def userInput = input message: "Please provide the required information for ${keyword}:", parameters: [text(defaultValue: 'default_value', description: "Enter your input for ${keyword}:", name: keyword)]
                            echo "User input for ${keyword}: ${userInput}"
                            yamlContent += "${keyword}: ${userInput}\n"
                        }
                    }

                    if (yamlContent) {
                        writeFile file: "${WORKSPACE}/input_values.yaml", text: yamlContent
                        echo "YAML file created with input values."
                    } else {
                        echo 'Neither OSTRICH nor CHICKEN was found in the text file.'
                    }
                }
            }
        }
        stage('Final stage') {
            steps {
                sh '''
                  cat "${WORKSPACE}/input_values.yaml"
                '''
            }
        }
    }
}